Simple signin page
netoary/programacao-avancada pull request #41
Opened 2021-05-30 14:59 UTC by VRavaglia

## Proposta
Página simples de Login sem nenhuma funcionalidade implementada, apenas redireciona para a página principal.

## Comentário para revisores

Apenas a parte visual foi implementada. Fonte: https://github.com/mui-org/material-ui/tree/master/docs/src/pages/getting-started/templates/sign-in

2021-05-30 16:20 UTC, PauloHMattos requested changes

2021-05-30 16:20 UTC, PauloHMattos commented on client/src/routes/SignIn.js
> +        Your Website
Trocar pro nome do nosso projeto ou tirar

2021-05-31 18:00 UTC, VRavaglia commented on client/src/routes/SignIn.js
> +        Your Website
Achei melhor remover

2021-05-31 18:24 UTC, PauloHMattos commented
O  package-lock.json deveria ter sido removido mesmo?

2021-05-31 18:30 UTC, PauloHMattos approved these changes

2021-05-31 18:30 UTC, merged