Some aesthetic changes in the Sign in page
netoary/programacao-avancada pull request #49
Opened 2021-06-12 22:28 UTC by netoary

## Proposta
_O que esse PR implementa/corrige?_

## Status do PR
- [ ] Testes manuais
- [ ] Testes unitários
- [ ] Testes de integração
- [ ] Documentação criada

## Comentário para revisores

## Comentários para teste

2021-06-13 17:10 UTC, netoary commented on client/package.json
> +    "react-google-button": "^0.7.2",
acho que não precisa mais disso

2021-06-13 17:10 UTC, netoary commented on server/package.json
> +    "react-google-button": "^0.7.2"
nem aqui

2021-06-14 12:33 UTC, PauloHMattos requested changes

2021-06-14 12:33 UTC, PauloHMattos commented on client/package.json
> +    "react-google-button": "^0.7.2",
```suggestion
```

2021-06-14 12:33 UTC, PauloHMattos commented on server/package.json
> +    "react-google-button": "^0.7.2"
```suggestion
```

2021-06-14 12:34 UTC, PauloHMattos approved these changes

2021-06-14 12:58 UTC, ofgabriel commented on client/Dockerfile.dev
> +RUN npm update chokidar
Não entendi muito bem o objetivo de atualizar essa dependência toda vez que construir a imagem. Sugeriria remover essa parte.

2021-06-14 12:58 UTC, ofgabriel commented on client/src/routes/SignIn.js
> +    // margin: 0,
A intenção era realmente manter essas linhas comentadas nesse componente? Sugiro remover qualquer código comentado.

2021-06-14 13:04 UTC, ofgabriel commented on server/package.json
> +    "qs": "^6.10.1",
Essa vírgula tá quebrando o arquivo.
```suggestion
    "qs": "^6.10.1"
```

2021-06-16 20:59 UTC, merged